/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hyperledger.orion.sdk;

import types.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}

