/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package orion.sdk.java;

import types.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}

